# Correspondencia entre el nombre/code que usamos en data/elo.csv
# y el nombre de equipo tal como aparece en el CSV de resultados históricos.
#
# Si en el futuro cambias la fuente de datos históricos, es probable que
# solo tengas que ajustar esta tabla (los nombres en inglés de la derecha).

OUR_NAME_TO_DATASET_NAME = {
    "Espana": "Spain",
    "Inglaterra": "England",
    "Francia": "France",
    "Portugal": "Portugal",
    "Paises Bajos": "Netherlands",
    "Noruega": "Norway",
    "Belgica": "Belgium",
    "Suiza": "Switzerland",
    "Alemania": "Germany",
    "Croacia": "Croatia",
    "Dinamarca": "Denmark",
    "Italia": "Italy",
    "Turquia": "Turkey",
    "Austria": "Austria",
    "Ucrania": "Ukraine",
    "Escocia": "Scotland",
    "Grecia": "Greece",
    "Serbia": "Serbia",
    "Suecia": "Sweden",
    "Kosovo": "Kosovo",
    "Hungria": "Hungary",
    "Polonia": "Poland",
    "Irlanda": "Republic of Ireland",
    "Gales": "Wales",
    "Eslovenia": "Slovenia",
    "Republica Checa": "Czech Republic",
    "Eslovaquia": "Slovakia",
    "Georgia": "Georgia",
    "Israel": "Israel",
    "Rumania": "Romania",
    "Albania": "Albania",
    "Irlanda del Norte": "Northern Ireland",
    "Bosnia-Herzegovina": "Bosnia and Herzegovina",
    "Macedonia del Norte": "North Macedonia",
    "Islandia": "Iceland",
    "Finlandia": "Finland",
    "Bielorrusia": "Belarus",
    "Montenegro": "Montenegro",
    "Bulgaria": "Bulgaria",
    "Luxemburgo": "Luxembourg",
    "Kazajistan": "Kazakhstan",
    "Islas Feroe": "Faroe Islands",
    "Armenia": "Armenia",
    "Estonia": "Estonia",
    "Azerbaiyan": "Azerbaijan",
    "Chipre": "Cyprus",
    "Letonia": "Latvia",
    "Lituania": "Lithuania",
    "Moldavia": "Moldova",
    "Malta": "Malta",
    "Andorra": "Andorra",
    "Gibraltar": "Gibraltar",
    "Liechtenstein": "Liechtenstein",
    "San Marino": "San Marino",
}
